### ISSUE TITLE
Do this work in a fork of 0ad/0ad?

### ISSUE THREAD

**Issue by leper** [0ADMods/resource_agnostic#1]
Might make merging some thing easier. Would likely also allow partial merges (as some of the code changes I've seen would be nice to have (now)).

**Comment by s0600204** [comment]
Apologies for the delay in responding - work suddenly got rather busy.

To answer your question: I'm not sure, I tend to track/copy-paste from SVN. I'll look into it.

And thanks for looking through the repo, and for your comments!

**Comment by s0600204** [comment]
Here: https://github.com/s0600204/0ad/tree/resource_agnostic

---

And a note to myself, just in case I need to repeat the process, the appropriate command was `git cherry-pick -Xsubpath=binaries/data/mods/public {rev1}...{rev2}`

**Comment by s0600204** [comment]
A patch based on code from the above branch has been submitted to http://trac.wildfiregames.com/ticket/3934

**Comment by s0600204** [comment]
The work in this repository has now been merged into core 0AD - https://trac.wildfiregames.com/changeset/18964.

Thus, I'm closing this issue.
